### ISSUE TITLE
커밋 컨벤션 정하기

### ISSUE THREAD

**Issue by ckrb63** [DevReader/CleanCode#5]
## Issue
- 커밋 컨벤션이 없어서 PR이 일관성이 없음

## To do
- 커밋 컨벤션 정하기
- 커밋 컨벤션 정한 내용 root directory README.md에 반영하기

**Comment by mouse0429** [comment]
커밋 컨벤션 설정해 README.md 에 반영해두었습니다. 
다음 스터디에서 괜찮은지 이야기 나누고 추가 수정 진행하면 좋을 것 같습니다! 해당 수정 사항까지 반영한 후에 이슈 닫도록 하겠습니다!

**Comment by ckrb63** [comment]
일단 이번 주는 올려주신 커밋 컨벤션 기반해서 커밋하겠습니다~
