### ISSUE TITLE
Organization 이미지 올리기

### ISSUE THREAD

**Issue by ckrb63** [DevReader/CleanCode#6]
## Issue
- org에 이미지 로고가 없으니 들어갈 때 헷갈림

## Todo
- 이미지 로고 구해오기(만들기, 찾기...)
- org 이미지 교체하기

**Comment by mouse0429** [comment]
어떤 로고로 할까 고민하다가 책 읽는 동물로하면 좋을 것 같아서.. 책 읽는 너구리로 했습니다
추후 더 좋은 로고/사진이 생긴다면 편하게 교체해주세요!
